### PR TITLE
Missing numpy functions

### PR DESCRIPTION
**Pull request by AngelEzquerra**
This PR adds a number of missing numpy functions:
- tril, triu: These were already implemented but not exported nor tested
- tri
- geomspace
- sinc
- meshgrid
- all / any
- flatten / roll

I'd like to add more but I think this is a good first set.

### CODE REVIEW

**Review by mratsim — APPROVED** [review]
Thanks, excellent

**Comment by AngelEzquerra** [comment]
I rebased this branch on top of the latest master branch.

**Comment by AngelEzquerra** [comment]
Added missing `flatten` and `roll` functions.

**Comment by Vindaar** [comment]
Also great work on this! :partying_face: 

After merging the other two (and having dropped 1.4 support), CI should pass for this one too. Can never remember whether you'll need to rebase onto the then-master without 1.4 though.

**Pull request merged**
