### PR TITLE
[Blocked by upstream bug] Change Tensor backend to pointer+length

### PR DESCRIPTION
**Pull request by mratsim**
This PR changes the CPU tensor backend to Laser pointer+length.

This would help on the issues tagged laser: https://github.com/mratsim/Arraymancer/issues?q=is%3Aissue+label%3ALaser+is%3Aopen

## Changing the backend

The current backend is using Nim sequences, this limits interoperability with other libraries and framework, in particular, having Arraymancer being just a view over a memory buffer described by pointer + length would allow zero-copy operations with NumPy, PyTorch and Tensorflow.

An additional benefit is enabling custom allocator (#419) which would be useful for distributed computing, NUMA-aware allocators and for situations where it's desirable to use the stack for example.

To provide deep immutability checks even with pointer object, a scheme using distinct type has been implemented:

https://github.com/mratsim/Arraymancer/blob/1a68830b14d3a8170d3918d0aba44369411ff205/src/laser/tensor/datatypes.nim#L12-L14

https://github.com/mratsim/Arraymancer/blob/1a68830b14d3a8170d3918d0aba44369411ff205/src/laser/tensor/datatypes.nim#L77-L89

https://github.com/mratsim/Arraymancer/blob/1a68830b14d3a8170d3918d0aba44369411ff205/src/laser/tensor/datatypes.nim#L105-L112

## Iterators

The current map_inline/map2_inline/map3_inline and apply_inline/apply2_inline/apply3_inline have several limits:
1. We need a variadic version that can handle arbitrary number of tensor to iterate onto. This limitation caused an inefficient iteration in GRU for example: https://github.com/mratsim/Arraymancer/blob/8acfd686b96a223dfe31803978b3915ab46e699f/src/nn_primitives/nnp_gru.nim#L76-L88

  Instead we could fuse all of those iterations and avoid intermediate tensors, similar to Intel Nervana Neon: https://github.com/NervanaSystems/neon/blob/8c3fb8a9/neon/layers/recurrent.py#L710-L723

2. The `x`, `y`, `z` arbitrary injected variables seem to come out-of-nowhere Laser forEach will lead to more readable code as the variables can use any name: https://github.com/numforge/laser/blob/d1e6ae6106564bfb350d4e566261df97dbb578b3/benchmarks/loop_iteration/iter_bench_prod.nim#L87-L90
  ```Nim
proc mainBench_libImpl(a, b, c: Tensor, nb_samples: int) =
  bench("Production implementation for tensor iteration"):
    forEach o in output, x in a, y in b, z in c:
      o = x + y - sin z
  ```

3. The map_inline/map2_inline/map3_inline and apply_inline/apply2_inline/apply3_inline lead to extreme code duplication to efficiently handle the contiguous and non-contiguous cases:
- https://github.com/mratsim/Arraymancer/blob/8acfd686b96a223dfe31803978b3915ab46e699f/src/tensor/private/p_accessors.nim#L208-L245
- https://github.com/mratsim/Arraymancer/blob/8acfd686b96a223dfe31803978b3915ab46e699f/src/tensor/private/p_accessors.nim#L98-L131
The new code would only duplicate an iteration body twice whatever the number of input tensors, instead of 4 times for the tripleStridedIteration

4. The new code is also about 15% faster according to benchmark https://github.com/numforge/laser/blob/d1e6ae6106564bfb350d4e566261df97dbb578b3/benchmarks/loop_iteration/iter_bench.nim#L140-L178 when iterating on strided tensors (that often result from slicing/reshaping). In the benchmark the old scheme is "Per tensor reference iteration" while the new one is "Fused per tensor reference iteration".
The main difference is that instead of having one of such loop per tensor: https://github.com/mratsim/Arraymancer/blob/1a68830b14d3a8170d3918d0aba44369411ff205/src/laser/strided_iteration/foreach_common.nim#L102-L120, a single loop updates all tensors iteration state.

### CODE REVIEW

**Comment by mratsim** [comment]
## Blocking:

Currently the compiler crashes without any error when compiling:

```
nim c -o:build/tests_tensor_part01 -r tests/_split_tests/tests_tensor_part01.nim
```

The stacktrace with `koch temp c` on the latest commit https://github.com/nim-lang/Nim/commit/357edd86b429dfaa3c24dedabdad0eb68915616f is

```
[...]
Hint: io_hdf5 [Processing]
/home/beta/Programming/Nim/Arraymancer/src/io/io_hdf5.nim(8, 24) Warning: import os.nim instead; ospaths is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/src/io/io.nim(13, 16) Warning: imported and not used: 'nimhdf5' [UnusedImport]
Hint: stats [Processing]
Hint: nlp [Processing]
Hint: tokenizers [Processing]
/home/beta/Programming/Nim/Arraymancer/src/nlp/tokenizers.nim(10, 20) template/generic instantiation of `items` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/accessors.nim(49, 19) template/generic instantiation of `stridedIteration` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/private/p_accessors.nim(137, 28) Warning: Use unsafe_raw_data instead; dataArray is deprecated [Deprecated]
Hint: einsum [Processing]
/home/beta/Programming/Nim/Arraymancer/src/tensor/einsum.nim(239, 22) Warning: Deprecated since version 0.18.1; All functionality is defined on 'NimNode'.; ident is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/src/tensor/einsum.nim(239, 31) Warning: Deprecated since version 0.18.0: Use 'ident' or 'newIdentNode' instead.; toNimIdent is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/src/tensor/einsum.nim(239, 28) Warning: Deprecated since version 0.18.1; Use '==' on 'NimNode' instead.; == is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/src/tensor/einsum.nim(265, 25) Warning: Deprecated since version 0.18.1; All functionality is defined on 'NimNode'.; ident is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/src/tensor/einsum.nim(265, 34) Warning: Deprecated since version 0.18.0: Use 'ident' or 'newIdentNode' instead.; toNimIdent is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/src/tensor/einsum.nim(265, 31) Warning: Deprecated since version 0.18.1; Use '==' on 'NimNode' instead.; == is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/src/tensor/einsum.nim(377, 10) Hint: 'enumerateIdx' is declared but not used [XDeclaredButNotUsed]
Hint: unittest [Processing]
Hint: terminal [Processing]
Hint: colors [Processing]
Hint: termios [Processing]
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(19, 7) template/generic instantiation of `suite` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(91, 8) template/generic instantiation of `test` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(94, 17) template/generic instantiation of `items` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/accessors.nim(49, 19) template/generic instantiation of `stridedIteration` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/private/p_accessors.nim(137, 28) Warning: Use unsafe_raw_data instead; dataArray is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(19, 7) template/generic instantiation of `suite` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(91, 8) template/generic instantiation of `test` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(98, 17) template/generic instantiation of `items` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/accessors.nim(49, 19) template/generic instantiation of `stridedIteration` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/private/p_accessors.nim(137, 28) Warning: Use unsafe_raw_data instead; dataArray is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(19, 7) template/generic instantiation of `suite` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(119, 8) template/generic instantiation of `test` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(122, 17) template/generic instantiation of `items` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/accessors.nim(49, 19) template/generic instantiation of `stridedIteration` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/private/p_accessors.nim(137, 28) Warning: Use unsafe_raw_data instead; dataArray is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(19, 7) template/generic instantiation of `suite` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(133, 8) template/generic instantiation of `test` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(137, 7) template/generic instantiation of `check` from here
/home/beta/Programming/Nim/Nim/lib/pure/unittest.nim(670, 14) template/generic instantiation of `==` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/operators_comparison.nim(24, 18) template/generic instantiation of `zip` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/accessors.nim(139, 23) template/generic instantiation of `dualStridedIteration` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/private/p_accessors.nim(176, 31) Warning: Use unsafe_raw_data instead; dataArray is deprecated [Deprecated]
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(19, 7) template/generic instantiation of `suite` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(133, 8) template/generic instantiation of `test` from here
/home/beta/Programming/Nim/Arraymancer/tests/tensor/test_init.nim(137, 7) template/generic instantiation of `check` from here
/home/beta/Programming/Nim/Nim/lib/pure/unittest.nim(670, 14) template/generic instantiation of `==` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/operators_comparison.nim(24, 18) template/generic instantiation of `zip` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/accessors.nim(139, 23) template/generic instantiation of `dualStridedIteration` from here
/home/beta/Programming/Nim/Arraymancer/src/tensor/private/p_accessors.nim(177, 31) Warning: Use unsafe_raw_data instead; dataArray is deprecated [Deprecated]
Traceback (most recent call last)
/home/beta/Programming/Nim/Nim/compiler/nim.nim(118) nim
/home/beta/Programming/Nim/Nim/compiler/nim.nim(95) handleCmdLine
/home/beta/Programming/Nim/Nim/compiler/cmdlinehelper.nim(77) loadConfigsAndRunMainCommand
/home/beta/Programming/Nim/Nim/compiler/main.nim(190) mainCommand
/home/beta/Programming/Nim/Nim/compiler/main.nim(92) commandCompileToC
/home/beta/Programming/Nim/Nim/compiler/modules.nim(143) compileProject
/home/beta/Programming/Nim/Nim/compiler/modules.nim(84) compileModule
/home/beta/Programming/Nim/Nim/compiler/passes.nim(216) processModule
/home/beta/Programming/Nim/Nim/compiler/passes.nim(86) processTopLevelStmt
/home/beta/Programming/Nim/Nim/compiler/sem.nim(600) myProcess
/home/beta/Programming/Nim/Nim/compiler/sem.nim(568) semStmtAndGenerateGenerics
/home/beta/Programming/Nim/Nim/compiler/semstmts.nim(2239) semStmt
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(995) semExprNoType
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2782) semExpr
/home/beta/Programming/Nim/Nim/compiler/importer.nim(218) evalImport
/home/beta/Programming/Nim/Nim/compiler/importer.nim(188) impMod
/home/beta/Programming/Nim/Nim/compiler/importer.nim(158) myImportModule
/home/beta/Programming/Nim/Nim/compiler/modules.nim(98) importModule
/home/beta/Programming/Nim/Nim/compiler/modules.nim(84) compileModule
/home/beta/Programming/Nim/Nim/compiler/passes.nim(210) processModule
/home/beta/Programming/Nim/Nim/compiler/passes.nim(86) processTopLevelStmt
/home/beta/Programming/Nim/Nim/compiler/sem.nim(600) myProcess
/home/beta/Programming/Nim/Nim/compiler/sem.nim(568) semStmtAndGenerateGenerics
/home/beta/Programming/Nim/Nim/compiler/semstmts.nim(2239) semStmt
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(995) semExprNoType
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2749) semExpr
/home/beta/Programming/Nim/Nim/compiler/semstmts.nim(2179) semStmtList
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2646) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(977) semDirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(870) afterCallActions
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(34) semTemplateExpr
(134 calls omitted) ...
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2521) matches
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2458) matchesAux
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2260) prepareOperand
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(49) semOperand
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2673) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(892) semIndirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(1413) semFieldAccess
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(1278) builtinFieldAccess
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(64) semExprWithType
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2673) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(899) semIndirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2671) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(976) semDirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(825) semOverloadedCallAnalyseEffects
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(528) semOverloadedCall
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(331) resolveOverloads
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(93) pickBestCandidate
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2521) matches
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2458) matchesAux
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2260) prepareOperand
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(49) semOperand
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2716) semExpr
/home/beta/Programming/Nim/Nim/compiler/semstmts.nim(1495) semLambda
/home/beta/Programming/Nim/Nim/compiler/semstmts.nim(1365) semParamList
/home/beta/Programming/Nim/Nim/compiler/semtypes.nim(1189) semProcTypeNode
/home/beta/Programming/Nim/Nim/compiler/semtypes.nim(1145) semParamType
/home/beta/Programming/Nim/Nim/compiler/semtypes.nim(1688) semTypeNode
/home/beta/Programming/Nim/Nim/compiler/semtypes.nim(1590) semTypeof
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(64) semExprWithType
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2671) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(977) semDirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(869) afterCallActions
/home/beta/Programming/Nim/Nim/compiler/sem.nim(471) semMacroExpr
/home/beta/Programming/Nim/Nim/compiler/sem.nim(414) semAfterMacroCall
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2646) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(977) semDirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(869) afterCallActions
/home/beta/Programming/Nim/Nim/compiler/sem.nim(471) semMacroExpr
/home/beta/Programming/Nim/Nim/compiler/sem.nim(414) semAfterMacroCall
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2671) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(976) semDirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(822) semOverloadedCallAnalyseEffects
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(536) semOverloadedCall
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(497) semResolvedCall
/home/beta/Programming/Nim/Nim/compiler/seminst.nim(388) generateInstance
/home/beta/Programming/Nim/Nim/compiler/seminst.nim(148) instantiateBody
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(1753) semProcBody
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2749) semExpr
/home/beta/Programming/Nim/Nim/compiler/semstmts.nim(2179) semStmtList
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2747) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(1705) semAsgn
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(64) semExprWithType
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2671) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(976) semDirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(825) semOverloadedCallAnalyseEffects
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(528) semOverloadedCall
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(331) resolveOverloads
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(93) pickBestCandidate
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2521) matches
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2458) matchesAux
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2260) prepareOperand
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(49) semOperand
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2673) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(899) semIndirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(2671) semExpr
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(976) semDirectOp
/home/beta/Programming/Nim/Nim/compiler/semexprs.nim(825) semOverloadedCallAnalyseEffects
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(528) semOverloadedCall
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(331) resolveOverloads
/home/beta/Programming/Nim/Nim/compiler/semcall.nim(93) pickBestCandidate
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2521) matches
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2459) matchesAux
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2170) paramTypesMatch
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(2014) paramTypesMatchAux
/home/beta/Programming/Nim/Nim/compiler/sigmatch.nim(1488) typeRel
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(715) prepareMetatypeForSigmatch
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(120) replaceTypeVarsT
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(514) replaceTypeVarsTAux
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(391) handleGenericInvocation
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(120) replaceTypeVarsT
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(608) replaceTypeVarsTAux
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(242) replaceTypeVarsN
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(199) replaceTypeVarsN
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(120) replaceTypeVarsT
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(514) replaceTypeVarsTAux
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(391) handleGenericInvocation
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(120) replaceTypeVarsT
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(598) replaceTypeVarsTAux
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(120) replaceTypeVarsT
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(608) replaceTypeVarsTAux
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(242) replaceTypeVarsN
/home/beta/Programming/Nim/Nim/compiler/semtypinst.nim(221) replaceTypeVarsN
/home/beta/Programming/Nim/Nim/compiler/msgs.nim(558) internalError
/home/beta/Programming/Nim/Nim/compiler/msgs.nim(529) liMessage
/home/beta/Programming/Nim/Nim/compiler/msgs.nim(356) handleError
/home/beta/Programming/Nim/Nim/compiler/msgs.nim(346) quit
FAILURE
```

**Comment by mratsim** [comment]
So I narrowed down the refcounting GC bug to one of those 3 tests:
- test_display
- test_higherorder
- test_ufunc

Commonalities:
- all rely on higher order templates map/apply
- all have at least a test that involve mapping a string

Issue can be reliably detected in its own module by wrapping tests into a proc and avoiding globals (globals have the same lifetime as the whole program) and then calling GC_fullcollect or GC_collectZct

**Comment by mratsim** [comment]
Smaller reproducible example

```Nim
import ../src/arraymancer

proc stringify(n: int): string = $n

proc main() =
  let a = @[@[2,4,8],@[3,9,27]]
  let ta = a.toTensor()

  let strTa = ta.map(stringify)

main()
GC_fullCollect()
```

**Comment by mratsim** [comment]
Some benches to investigate:

20% regression on the simple xor https://github.com/mratsim/Arraymancer/blob/v0.6.0/benchmarks/ex01_xor.nim
image
Note: limited impact of threads:on which is known to to make `allocShared` an allocation bottleneck due to a lock (note the proper solution is not to avoid allocShared but avoid allocating or implement a custom allocator) from Weave benches https://github.com/mratsim/weave/commit/5d1bfb44e354c364c2cf1b2590ae7c80a4a472dd
image

On a larger scale benchmark there is no perf diff:
image
image

Note the scaling is quite bad from my old dual core to my 18-core due to MNIST being about 28 by 28 images, see old benches: https://github.com/mratsim/Arraymancer/pull/303

**Comment by mratsim** [comment]
@brentp @HugoGranstrom @Vindaar if you can confirm that this PR doesn't completely breaks your code that would be very helpful.

Otherwise I can do a 0.7 release with the Numpy indexing and then work on this change for 0.8

**Comment by HugoGranstrom** [comment]
Neat! Great work! 🤩 All NumericalNim's tests pass so this shouldn't be a problem there.

**Comment by Vindaar** [comment]
Awesome work! I'll let you know later today!

**Comment by Vindaar** [comment]
Ok, I can already report that in ggplotnim I stumble on problems, when a tensor of my variant kind `Value` (for object columns with mixed types) is created.

Happens here:
https://github.com/Vindaar/ggplotnim/blob/master/src/ggplotnim/dataframe/column.nim#L67

and doesn't compile because of here:
https://github.com/mratsim/Arraymancer/blob/laser-tensor-iterator/src/laser/tensor/allocator.nim#L30

with:

```
/home/basti/CastData/ExternCode/ggplotnim/src/ggplotnim/dataframe/column.nim(67, 44) template/generic instantiation of `newTensor` from here
/home/basti/src/nim/arraymancer/src/laser/tensor/initialization.nim(178, 18) template/generic instantiation of `allocCpuStorage` from here
/home/basti/src/nim/arraymancer/src/laser/tensor/allocator.nim(30, 23) Error: type mismatch: got <ptr UncheckedArray[Value], int>
but expected one of: 
proc newSeq[T](len = 0.Natural): seq[T]
  first type mismatch at position: 1
  required type for len: Natural
  but expression 'storage.raw_buffer' is of type: ptr UncheckedArray[Value]
proc newSeq[T](s: var seq[T]; len: Natural)
  first type mismatch at position: 1
  required type for s: var seq[T]
  but expression 'storage.raw_buffer' is of type: ptr UncheckedArray[Value]

expression: newSeq(storage.raw_buffer, size)
```

I'll be on lunch break now. I'll see if this is something I can help with afterwards, if you haven't taken a look at it by then.

**Comment by brentp** [comment]
my stuff seems to be working. thank you.

**Comment by mratsim** [comment]
@Vindaar I'll park this PR and wait until https://github.com/nim-lang/Nim/issues/13193 is solved then.

**Comment by Vindaar** [comment]
Ok sorry, kinda unfortunate!

Let's hope the upstream issue is fixed quickly!

**Comment by mratsim** [comment]
From the discussion, @Araq already tried and it's non-trivial as it creates a cascade of regressions https://irclogs.nim-lang.org/21-04-2020.html#14:43:57

**Comment by Clonkk** [comment]
With release 1.4 of Nim coming and many bugs fixed in gc:arc and gc:orc is there any chance to have update / progress on this issue ?

I've seen in several threads on the forum that many people (including me) are excited to use Arraymancer with ARC/ORC :)

**Comment by mratsim** [comment]
I can't merge this PR until this is solved https://github.com/nim-lang/Nim/issues/13193

**Comment by Araq** [comment]
What does it mean to "solve"  nim-lang/Nim#13193 ? Clyybber said you need to use ``CpuStorage[T: type]``

**Comment by mratsim** [comment]
From IRC: https://irclogs.nim-lang.org/21-04-2020.html#14:46:18

image

**Comment by Vindaar** [comment]
As an FYI I've finished a rebase of this on current master. I'm currently fixing up some things which were rebased incorrectly (either by me choosing the wrong branch maybe or by git itself?).

Just felt like letting people know that this is finally going forward.

The idea is to replace the current logic using `when T.supportsCopyMem` (in code) and `when not (T is string or T is ref)` (in `Tensor` definition) by a custom type class of supported types we know can be mem copied. That way it should be possible to work at least for the majority of use cases using pointer + length and `seq` as a fallback option.

**Comment by Clonkk** [comment]
Will this change the API (such as accessor) ? 

Will it change how low-level Tensor transformation is done (copyMem tensor into buffer etc.) ?

**Comment by Vindaar** [comment]
> Will this change the API (such as accessor) ?

The API will remain unchanged (with a few small exceptions, e.g. `toRawSeq` won't be possible for ptr + length of course; adding a normal `toSeq` proc, which copies might be a good idea though).

> Will it change how low-level Tensor transformation is done (copyMem tensor into buffer etc.) ?

Yes, it will. But most of this will happen behind the scenes. In case you have a raw ptr array you then will be able to wrap it in a Tensor and perform all arraymancer functionality without copying.

**Comment by mratsim** [comment]
merged #477

**Pull request closed without merging**
