### PR TITLE
Replace deprecated `dataArray` with `toUnsafeView`

### PR DESCRIPTION
**Pull request by asnt**
Following the [hint](https://github.com/mratsim/Arraymancer/blob/66372d249b849102fd196345a08d4563d904751a/src/arraymancer/tensor/data_structure.nim#L188).

### CODE REVIEW

**Comment by asnt** [comment]
Tests fail with Nim 1.0.x.

**Comment by mratsim** [comment]
image


The issue can probably be solved by:
- importing std/typetraits in tensor/initialization.nim
- exporting std/typetraits in tensor/algorithms.nim
- using `mixin DistinctBase` in toUnsafeView

https://github.com/mratsim/Arraymancer/runs/4669608372?check_suite_focus=true#step:23:390

This looks like another instance of the generic sandwich https://github.com/nim-lang/Nim/issues/11225

**Comment by asnt** [comment]
@mratsim Thank you. I tried the suggestion without luck.
Does `distinctBase` exist in nim 1.0.x?:
```nim
# test.nim
import std/typetraits
echo type(distinctBase)
``` 
```bash
# Not OK.
$ choosenim 1.0.10
$ nim c -r test.nim
[...]
/home/u/Arraymancer/test.nim(2, 11) Error: undeclared identifier: 'distinctBase'
# OK.
$ choosenim 1.2.16
$ nim c -r test.nim
[...]
None
```

**Comment by Vindaar** [comment]
Closing as unnecessary as mentioned by Clonkk. Thanks @asnt though and sorry for not getting it merged!

**Pull request closed without merging**
