### PR TITLE
Improve the display of rank 2 column Tensors

### PR DESCRIPTION
**Pull request by AngelEzquerra**
This also adds a little more documentation to the Flatten NN layer.

### CODE REVIEW

**Comment by Vindaar** [comment]
Sorry, I overlooked the actual PR! Could you maybe add a single test case for the display of a simple transposed 1D tensor?

**Comment by AngelEzquerra** [comment]
> Sorry, I overlooked the actual PR! Could you maybe add a single test case for the display of a simple transposed 1D tensor?

That is a good idea. I just pushed an additional commit which adds a new display test.

**Comment by Vindaar** [comment]
You accidentally also commited the `test_display` binary.

**Comment by Vindaar** [comment]
Thanks a lot!

**Pull request merged**
