### PR TITLE
add stricteffects support

### PR DESCRIPTION
**Pull request by xflywind**
ref https://github.com/nim-lang/Nim/pull/19380

### CODE REVIEW

**Comment by mratsim** [comment]
Shouldn't all higher order functions be concerned?

Like

https://github.com/mratsim/Arraymancer/blob/20e0dc371caab1fa6a80edb6e6554e164cdbc238/src/arraymancer/tensor/higher_order_applymap.nim#L149-L171

**Comment by xflywind** [comment]
IMO only procs with effects (`noSideEffect` or `gcsafe`) should be concerned?

**Comment by xflywind** [comment]
Make sense, thanks!

**Comment by mratsim** [comment]
Then I think the last ones are those here: https://github.com/mratsim/Arraymancer/blob/20e0dc3/src/arraymancer/tensor/higher_order_foldreduce.nim#L69-L72

**Comment by xflywind** [comment]
My mistake, thank you!

**Review by mratsim — APPROVED** [review]

**Pull request merged**
