### PR TITLE
rename `newSeqUninit` in order to avoid conflicts with upstream

### PR DESCRIPTION
**Pull request by ringabout**
ref https://github.com/nim-lang/Nim/pull/22739

It's a private function so it shouldn't affect backwards compatibility.

### CODE REVIEW

**Comment by Vindaar** [comment]
I'm confused as to why we cannot keep the `when not declared` logic? I haven't fully understood the stdlib changes yet, sorry.

**Comment by ringabout** [comment]
It seems that https://github.com/mratsim/Arraymancer/blob/875ee6bf595a220a08827adeaee8a89722d2c8f2/src/arraymancer/laser/tensor/datatypes.nim#L37 uses refs, which is not supported by `newSeqUninit`.

But `newSeqUninit` is unavailable to types, which contain managed memory or have destructors.

**Comment by Vindaar** [comment]
Ohh, now I see. My confusion was that I assumed this PR here https://github.com/nim-lang/Nim/pull/22586 was merged already and based on Mamy's PR #591 I further assumed it was a drop in replacement for our custom one. 

And yes, the `CpuStorage` can either hold regular POD types or references. Thanks for the explanation.

What is the reason though for the restriction of the stdlib version to types that can be memcopied? The code currently doesn't do anything that seems to rely on that, no? 

I don't have a strong opinion on the name, `newSeqUninit2` is fine by me. Just trying to understand the restrictions.

**Comment by ringabout** [comment]
I think type bounding operations requires types to be initialized preemptively.

For instance, destructors or other type bounding operations might not work properly since `Ref` might be anything.
```nim
var x = newSeqNoInit[Ref](10)
```

**Comment by Vindaar** [comment]
But then what does our current code do? Or in other words, if I currently write:
```nim
type
  Foo = ref object
    x: float

var x = newSeqOfCap[Foo](10)
x.setLen(10)
```
wouldn't that be undefined behavior if I understand you correctly?

**Comment by ringabout** [comment]
`setLen` will initialize the sequence in v2 since its original length is smaller than the new length
```nim
var x = newSeqOfCap[Foo](10)
x.setLen(10)
```
so it is just another way of writing `vat x = newSeq[Foo](10)` with the same efficiency.

**Comment by Vindaar** [comment]
Ah, I see. But then that implies our implementation, `newSeqUninit2` now, is "broken" and doesn't actually do an "uninit" implementation anymore. 

So we need to merge the logic for `newSeqUninit2` to be something like this:

```nim
func newSeqUninit2*[T](len: Natural): seq[T] {.inline.} =
  ## Creates an uninitialzed seq if the type is plain old data. Falls back
  ## to a normal `newSeq` call for any non trivial data type.
  when supportsCopyMem(T):
    result = newSeqUninit[T](len)
  else:
    result = newSeq[T](len)
```

so that at least we get the desired behavior for mem copyable types.

**Comment by ringabout** [comment]
Indeed, I agree. It also need to be combined with `when declared(newSeqUninit)`.

**Comment by Vindaar** [comment]
Cool! Will you make the change or should I do it?

**Comment by ringabout** [comment]
Feel free to take over this PR, or do it in the following PRs. Thank you in advance!

**Comment by Vindaar** [comment]
Sorry for the delay. Will take care of this soon. Yesterday was a bit stressful. :)

**Comment by mratsim** [comment]
I think we can just delete newSeqUninit in Arraymancer actually, with the Laser PR, the storage for POD datatypes changed to ptr UncheckedArray:

https://github.com/mratsim/Arraymancer/blob/875ee6bf595a220a08827adeaee8a89722d2c8f2/src/arraymancer/laser/tensor/datatypes.nim#L39C1-L47

so CPU storage is only used for ref types and strings but the current impl will likely cause issues with destructors and we aren't optimizing for strings/ref types.

In fact, CpuStorage uses `newSeq` for alloc of tensors

https://github.com/mratsim/Arraymancer/blob/875ee6bf595a220a08827adeaee8a89722d2c8f2/src/arraymancer/laser/tensor/datatypes.nim#L86-L101

and newSeqUninit only for intermediate sequences when interfaces with C libraries like Lapack

https://github.com/search?q=repo%3Amratsim%2FArraymancer%20newSequninit&type=code

**Comment by Vindaar** [comment]
Good point actually.
The one exception is the `toRawSeq` implementation, but given that this is deprecated for good reason, I'd simply use a regular `newSeq` there instead and go ahead and removing our implementation.

**Pull request closed without merging**
